import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        secondary: "#dcfdff",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#002022",
        surface: "#131313",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed-variant": "#095300",
        "surface-tint": "#2ae500",
        primary: "#efffe3",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#00373a",
        "tertiary-fixed": "#ffdad6",
        "on-secondary-fixed-variant": "#004f53",
        "error-container": "#93000a",
        "secondary-fixed": "#6ff6ff",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#93000c",
        "primary-container": "#39ff14",
        "secondary-fixed-dim": "#00dce6",
        tertiary: "#fff8f7",
        "primary-fixed-dim": "#2ae500",
        "on-surface-variant": "#baccb0",
        "on-tertiary-fixed": "#410002",
        outline: "#85967c",
        "inverse-primary": "#106e00",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#022100",
        "on-primary-container": "#107100",
        "surface-container": "#201f1f",
        "surface-variant": "#353534",
        "surface-container-high": "#2a2a2a",
        "tertiary-container": "#ffd3ce",
        "on-background": "#e5e2e1",
        "outline-variant": "#3c4b35",
        "on-primary": "#053900",
        "surface-dim": "#131313",
        "on-tertiary": "#690006",
        "primary-fixed": "#79ff5b",
        "surface-container-highest": "#353534",
        "on-tertiary-container": "#c50015",
        "surface-bright": "#3a3939",
        "inverse-on-surface": "#313030",
        "on-secondary-container": "#006a6f",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#ffb4ab",
        "secondary-container": "#00f1fd",
        background: "#131313",
      },
      fontFamily: {
        display: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "terminal-code": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      spacing: {
        unit: "8px",
        "container-padding": "24px",
        gutter: "16px",
        "hud-margin": "32px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      animation: {
        scan: "scan 4s linear infinite",
        ticker: "ticker 30s linear infinite",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
        "flicker": "flicker 0.15s ease-in-out infinite",
      },
      keyframes: {
        scan: {
          "0%": { top: "0%" },
          "100%": { top: "100%" },
        },
        ticker: {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(-100%)" },
        },
        pulseGlow: {
          "0%, 100%": { opacity: "0.5" },
          "50%": { opacity: "1" },
        },
        flicker: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
      },
    },
  },
  plugins: [],
}
export default config
